<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>LEP</title>
		<link rel="shortcut icon" type="image/ico" href="<?=$this->pathMedia?>images/favicon.ico"/>
		<link rel="stylesheet" href="<?=$this->pathMedia?>librerias/Bootstrap/Bootstrap3.3.7/dist/css/bootstrap.min.css"/>
		<link rel="stylesheet" href="<?=$this->pathMedia?>librerias/font-awesome-4.7.0/css/font-awesome.min.css"/>
		<link rel="stylesheet" href="<?=$this->pathMedia?>css/styles.css"/>
		<link rel="stylesheet" href="<?=$this->pathMedia?>css/login.css"/>
		<?
			$user_agent = isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
			if( preg_match('/MSIE/i', $user_agent) )
			{
		?>
		<script type="text/javascript" src="<?=$this->pathMedia?>librerias/Jquery/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="<?=$this->pathMedia?>librerias/html5shiv-master/dist/html5shiv.min.js"></script>
		<script type="text/javascript" src="<?=$this->pathMedia?>librerias/Respond-master/dest/respond.min.js"></script>
		<? 
			}
			else 
			{
		?>
		<script type="text/javascript" src="<?=$this->pathMedia?>librerias/Jquery/jquery-3.2.1.min.js"></script>
		<? 
			}
		?>
		<script type="text/javascript" src="<?=$this->pathMedia?>librerias/Bootstrap/Bootstrap3.3.7/dist/js/bootstrap.min.js"></script>
		<script type="text/javascript">
			var path = "<?=Config::$configuration->get('server_path')?>/";
		</script>
		<script type="text/javascript" src="<?=$this->pathMedia?>js/functions.js"></script>
		<script type="text/javascript" src="<?=$this->pathMedia?>js/login_admin_afa.js"></script>
	</head>
	<body>
		<div class="container">
			
			<center> <img src="<?=$this->pathMedia?>images/logo.png" border="0" width="180" height="80" align="center" title="TELMEX está contigo"></img>
			<h5>Soporte Técnico LEP</h5></center>
			<form class="form-signin" id='form-login'>
				<div id="err-msg"></div>
				<label for="inputEmail" class="sr-only">Usuario</label>
				<input type="email" id="usuario" name="usuario" class="form-control" placeholder="Usuario" required="" autofocus="">
				<label for="inputPassword" class="sr-only">Password</label>
				<input type="password" id="passwd" name="passwd" class="form-control" placeholder="Contraseña" required="">
				<div class="checkbox">
				</div>
				<button class="btn btn-lg btn-warning btn-block" id="btn-login">Acceder</button>
			</form>	
			<center><p>Copyright &copy; Telmex. All rights reserved.</p></center>
		</div>
		<div id="modal-loader" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="modal-loader" data-backdrop="static" 
			data-keyboard="false">
			<div class="modal-dialog modal-sm" role="document">
				<i class="fa fa-spinner fa-pulse fa-5x fa-fw"></i>
				<span class="sr-only"> Loading... </span>
			</div>
		</div>
	</body>
</html>
