<div>
	<h4>Menu de opciones adminitración de AFA</h4>
	<hr>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-2">
			<a href="<?=Config::$configuration->get('server_path')?>/index.php/bitacoras/" type="button" class="btn btn-default">
				<i class="fa fa-address-book"></i><br>
				Ver Bitacoras
			</a>
		</div>
		<div class="col-md-2">
			<a href="<?=Config::$configuration->get('server_path')?>/index.php/adminafa/administrar_usuarios_afa/" type="button" class="btn btn-default">
				<i class="fa fa-users"></i><br>
				Administrar Usuarios
			</a>
		</div>
		<div class="col-md-2"></div>
		<div class="col-md-2"></div>
		<div class="col-md-2"></div>
	</div>
</div>
