
<div class="container-fluid">

	<div class="col-sm-12">
		<form class="form-inline" id="form-filtro">
			<div class="form-group">
				<label for="fecha_soporte">Desde:</label>
				<input type="text" class="form-control" id="fecha_soporte" name="fecha_soporte">
			</div>
			<div class="form-group">
				<label for="fecha_fin_falla">Hasta:</label>
				<input type="text" class="form-control" id="fecha_fin_falla" name="fecha_fin_falla" >
			</div>
			<div class="form-group">
				<label for="gerencia">Gerencia:</label>
				<select class="form-control" id="gerencia" name="gerencia">
					<option value="" selected>Todos</option>
					<option value="Lec">Lec</option>
					<option value="Let">Let</option>
					<option value="Leg">Leg</option>
					<option value="Lep">Lep</option>
				</select>
			</div>
			<button type="button" id="filtrar" class="btn btn-danger">Consultar</button>
			<button type="reset" id="limpiar" class="btn btn-default">Quitar Filtro</button>
		</form>
	</div>
	<hr><hr>


	<div class="col-sm-12">
		<p class='h4'>Total eventos: <strong id='total'></strong></p>
	</div>
	
	<div class="col-sm-12" id="contenido" style="font-size: 11px;">
		
		<div class="col-sm-3 itm" id='Proceso'></div>
		<div class="col-sm-3 itm" id='Liquidado'></div>
		<div class="col-sm-3 itm" id='Gerencias'></div>
		<div class="col-sm-3 itm" id='Promedio'></div>

	</div>


	<!-- Modal -->
	<div class="modal fade" id="modalDetalle" tabindex="-1" role="dialog" aria-labelledby="modalDetalleLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="modalDetalleLabel">Eventos en Proceso</h4>
				</div>
				<div class="modal-body">
					<div id="detalle" style="font-size: 11px;"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
					<!-- <button type="button" class="btn btn-primary">Save changes</button> -->
				</div>
			</div>
		</div>
	</div>
	<!-- <div class="col-sm-6" id="promedio">
	
	</div>

	<div class="col-sm-6" id="detalle">
	
	</div> -->

</div>