<style>
	.hiddenRow {
	    padding: 0 !important;
	}
</style>
<div class="container-fluid">
	
	<div class="row" id="div-division">
		
		<table class="table table-condensed table-bordered" id="table-division" style="border-collapse:collapse;">
		    <thead>
		        <tr>
		        	<th class="text-center">División</th>
		        	<th class="text-center" colspan="5" >Inventario</th>
		        </tr>
		    </thead>
		    <tbody class="text-12">
		    </tbody>
		</table>

	</div>

</div>