<div class="container-fluid">
	
	<div class="row">

		<div class="col-sm-12">
			<div id="container-form">
				<form class="form" id="form-reportes" style="padding: 0px 20px">
					<input type="hidden" id="id" name="id">
					<div class="form-group col-sm-12 col-md-3">
					    <label for="nombre">Ingeniero que Atiende</label>
					    <!-- <select class="form-control input-sm" name="nombre" id="nombre"></select> -->
					    <input type="text" class="form-control input-sm" name="nombre" id="nombre">
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="nombre_reporta">Ingeniero que Reporta</label>
					    <input type="text" class="form-control input-sm" name="nombre_reporta" id="nombre_reporta">
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="entidad">Entidad</label>
					    <input type="text" class="form-control input-sm" name="entidad" id="entidad" >
					    <!-- <select class="form-control input-sm" name="entidad" id="entidad">
					    	<option value="">Seleccionar</option>
					    	<option value="CNS III PUEBLA">CNS III PUEBLA</option>
					    	<option value="CORPORATIVO TRAFICO">CORPORATIVO TRAFICO</option>
					    </select> -->
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="evento">Evento</label>
					    <select class="form-control input-sm" name="evento" id="evento">
					    	<option value="">Seleccionar</option>
					    	<option value="Falla">Falla</option>
					    	<option value="Asesoría">Asesoría</option>
					    	<option value="Consultoría">Consultoría</option>
					    	<option value="Programado">Programado</option>
					    	<option value="Refacción">Refacción</option>
					    	<option value="Otro">Otro</option>
					    </select>
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="fecha_falla">Inicio de Falla</label>
					    <input type="text" class="form-control input-sm" name="fecha_falla" id="fecha_falla">
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="fecha_reporte_falla">Aviso a Soporte Técnico</label>
					    <input type="text" class="form-control input-sm" name="fecha_reporte_falla" id="fecha_reporte_falla">
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="fecha_soporte">Inicio de Soporte</label>
					    <input type="text" class="form-control input-sm" name="fecha_soporte" id="fecha_soporte">
					</div>

					<div class="form-group col-sm-12 col-md-3">
					    <label for="fecha_fin_falla">Fecha Fin Falla</label>
					    <input type="text" class="form-control input-sm" name="fecha_fin_falla" id="fecha_fin_falla">
					</div>
					
					<div class="form-group col-sm-12 col-md-3">
					    <label for="lugar">Lugar</label>
					    <input type="text" class="form-control input-sm" name="lugar" id="lugar">
					</div>

					<div class="form-group col-sm-12 col-md-2">
					    <label for="equipo">Equipo</label>
					    <input type="text" class="form-control input-sm" name="equipo" id="equipo">
					</div>

					<div class="form-group col-sm-12 col-md-2">
					    <label for="impacto">Impacto</label>
					    <select class="form-control input-sm" name="impacto" id="impacto">
					    	<option value="">Seleccionar</option>
					    	<option value="&amp;&amp;&amp;CA">&amp;&amp;&amp;CA</option>
							<option value="IMPCA">IMPCA</option>
							<option value="&amp;&amp;&amp;SA">&amp;&amp;&amp;SA</option>
							<option value="IMPSA">IMPSA</option>
							<option value="MIMPCA">MIMPCA</option>
							<option value="MIMPSA">MIMPSA</option>
					    </select>
					</div>

					<div class="form-group col-sm-12 col-md-5">
					    <label for="comentarios">Descripción</label>
					    <textarea class="form-control input-sm" name="comentarios" id="comentarios" cols="10" rows="1"></textarea>
					</div>

					<div class="form-group col-sm-12 col-md-6">
					    <label for="solucion">Solución</label>
					    <input type="text" class="form-control input-sm" name="solucion" id="solucion">
					</div>

					<div class="form-group text-center col-sm-12 col-md-12">
					    <button type="button" class="btn btn-primary" id="btn-guardar-reporte">Guardar</button>
					    <button type="reset" class="btn btn-success" id="">Limpiar</button>
					</div>

				</form>
			</div>
			
		</div>

		<div class="col-sm-12">
			<table class="table table-condensed table-11" id="table-reportes">
				<thead>
					<tr>
						<th>Detalle</th>
						<th>No Reporte</th>
						<th>Ingeniero</th>
						<th>Asunto</th>
						<th>Estatus</th>
						<th>Impacto</th>
						<th>Inicio de Falla</th>
						<th>Aviso a Soporte</th>
						<th>Inicio de Soporte</th>
						<th>Fin de Soporte</th>
						<th>Solución</th>
						<th>Fecha Escalación</th>
						<th>Escalado/Archivo</th>
					</tr>
				</thead>
				<tbody>
					
				</tbody>
			</table>
		</div>
		
	</div>



	<!-- MODAL CARGAR ANEXOS -->
	<div class="modal fade" id="modal-anexo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Cargar Archivos</h4>
				</div>
				<div class="modal-body">

				<div class="row">
					<div class='col-sm-12'><h5>Archivos Cargados</h5></div>
					<ul id="anexos_listado">
						
					</ul>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<form enctype="multipart/form-data" class="formulario" id="form-archivos">
							<input type="hidden" name="id_rep" id="id_rep">
							<div id="div-file" class="col-md-12 col-sm-12">
								<div class="form-group">
									<label for="file-soporte">Seleccione Documento</label>
									<input type="file" name="archivo" id="file-soporte" required data-msg="Adjunte un archivo">
									<p class="help-block">(.pdf, .xlsx, .docx )</p>
								</div>
								
								<!--div para visualizar mensajes-->
								<div class="messages"></div>
								<input type="button" class="btn btn-danger" value="Cargar Documento" id="btn-file" /><br />
							</div>
						</form>
					</div>
				</div>
					
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
					<!-- <button type="button" class="btn btn-primary">Save changes</button> -->
				</div>
			</div>
		</div>
	</div>


	<!-- MODAL FINALIZAR -->
	<div class="modal fade" id="modal-finalizar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header bg-success">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Finalizar Reporte</h4>
				</div>
				<div class="modal-body">

				<div class="row">
					<div class="col-sm-12">
						<form class="form" id="form-finalizar" style="padding: 0px 20px">

							<input type="hidden" id="id_rep_fin" name="id_rep_fin">
							<div class="form-group col-sm-12 col-md-6">
							    <label for="fecha_fin_falla_upd">Fin Falla</label>
							    <input type="text" class="form-control input-sm" name="fecha_fin_falla_upd" id="fecha_fin_falla_upd">
							</div>

							<div class="form-group col-sm-12 col-md-12">
							    <label for="solucion">Solución</label>
							    <textarea class="form-control" name="solucion" id="solucion" cols="10" rows="4"></textarea>
							</div>

						</form>
					</div>
				</div>
					
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
					<button type="button" class="btn btn-primary" id="btn-finalizar">Finalizar</button>
				</div>
			</div>
		</div>
	</div>

	<!-- MODAL ESCALADO A PROVEEDOR -->
	<div class="modal fade" id="modal-escalado" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header bg-danger">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Escalación a proveedor</h4>
				</div>
				<div class="modal-body">

				<div class="row">
					<div class="col-sm-12">
						<form class="form" id="form-escalado" style="padding: 0px 20px">

							<input type="hidden" id="id_rep_escalado" name="id_rep_escalado">
							<div class="form-group col-sm-12 col-md-6">
							    <label for="reporte_escalado">No. Reporte</label>
							    <input type="text" class="form-control input-sm" name="reporte_escalado" id="reporte_escalado">
							</div>

							<div class="form-group col-sm-12 col-md-6">
							    <label for="ingeniero_escalado">Ing. Atiende</label>
							    <input type="text" class="form-control input-sm" name="ingeniero_escalado" id="ingeniero_escalado">
							</div>

							<div class="form-group col-sm-12 col-md-6">
							    <label for="proveedor_escalado">Empresa</label>
							    <select  class="form-control input-sm" name="proveedor_escalado" id="proveedor_escalado"></select>
							    <!-- <input type="text"> -->
							</div>

							<div class="form-group col-sm-12 col-md-12">
							    <label for="solucion_escalado">Solución de Escalación</label>
							    <textarea class="form-control" name="solucion_escalado" id="solucion_escalado" cols="10" rows="4"></textarea>
							</div>

						</form>
					</div>
				</div>
					
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
					<button type="button" class="btn btn-primary" id="btn-escalado">Guardar</button>
				</div>
			</div>
		</div>
	</div>

</div>